sudo: required

services:
   - docker

before_install:
   - docker build -t aditishinde/node-app2 .
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker push aditishinde/node-app2
   - wget https://mirror.openshift.com/pub/openshift-v4/amd64/clients/oc-dec2/4.6/linux/

script:
   - docker run -p 8080:8080 -d aditishinde/node-app2
   - docker ps
   - oc version
   
    
  
