sudo: required

services:
   - docker

before_install:
   - gem install bundler --version '1.7.4'
   - docker build -t aditishinde/node-app2:1.0 .
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker push aditishinde/node-app2:1.0
   - wget https://mirror.openshift.com/pub/openshift-v4/amd64/clients/oc-dec2/4.6/linux/oc.tar.gz
   - tar -xzf oc.tar.gz
   - sudo -E env "PATH=$PATH" cp oc /bin
   - sudo -E env "PATH=$PATH" cp oc /usr/bin
   - sudo -E env "PATH=$PATH" chmod a+x /usr/bin/oc
   - sudo -E env "PATH=$PATH" chmod a+x /bin/oc

script:
   - docker run -p 8080:8080 -d aditishinde/node-app2:1.0
   - docker ps
   - oc login --token="$OC_TOKEN" --server="$OC_SERVER"
   - oc project "$PROJECT_NAME"
   - oc apply -f deployment.yaml 
  
   
    
  
