apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app-application
  namespace: aditi-poc
spec:
  project: default
  source:
    repoURL: https://github.com/aditi1800/node-app1.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: node-app-demo-aditi
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
