kind: Deployment
apiVersion: apps/v1
metadata:
  name: node-app2
  namespace: aditi-poc 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-app2
        deploymentconfig: node-app2
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: node-app2
          image: >-
            docker.io/aditishinde/node-app2:1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
