apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: docker.io/aditishinde/node-app2:latest
        ports:
        - containerPort: 8080
